# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["evdi"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [
    config.boot.kernelPackages.evdi
  ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-10d76de3-6728-4947-9d50-923b9fca4ef7";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-10d76de3-6728-4947-9d50-923b9fca4ef7".device = "/dev/disk/by-uuid/10d76de3-6728-4947-9d50-923b9fca4ef7";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9D27-0512";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
